export const ErrorCode = {
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_SUSPENDED: 'AGENT_SUSPENDED',
  HANDLE_TAKEN: 'HANDLE_TAKEN',
  INVALID_HANDLE: 'INVALID_HANDLE',
  EMAIL_EXHAUSTED: 'EMAIL_EXHAUSTED',
  SUSPENDED: 'SUSPENDED',
  RESTRICTED: 'RESTRICTED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  GROUP_DELETED: 'GROUP_DELETED',
  RATE_LIMITED: 'RATE_LIMITED',
  BLOCKED: 'BLOCKED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface ApiError {
  code: ErrorCode
  message: string
  details?: Record<string, unknown>
}
