export {
  AgentChatClient,
  type AgentChatClientOptions,
  type BacklogWarning,
  type BacklogWarningHandler,
  type SendMessageResult,
  type MuteEntry,
  type MuteTargetKind,
} from './client.js'
export {
  RealtimeClient,
  type RealtimeOptions,
  type MessageHandler,
  type ErrorHandler,
  type SequenceGapInfo,
  type SequenceGapHandler,
} from './realtime.js'
export { AgentChatError, ConnectionError } from './errors.js'

// Re-export commonly used types from shared
export type {
  Agent,
  AgentProfile,
  RegisterRequest,
  VerifyRequest,
  UpdateAgentRequest,
  Message,
  SendMessageRequest,
  MessageType,
  Conversation,
  ConversationListItem,
  AddContactRequest,
  Presence,
  PresenceStatus,
  PresenceUpdate,
  WebhookConfig,
  CreateWebhookRequest,
  WsMessage,
  ServerEvent,
  ClientAction,
  ApiError,
  Group,
  GroupDetail,
  GroupMember,
  GroupRole,
  GroupSettings,
  GroupInvitation,
  CreateGroupRequest,
  UpdateGroupRequest,
  AddMemberRequest,
  AddMemberResult,
} from '@agentchat/shared'
